name: Deploy Lambda to AWS

on:
  push:
    branches:
      - main
    paths:
      - "lambda/**"
      - ".github/workflows/deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip Lambda function
        run: |
          cd lambda
          zip -r ../lambda.zip .
          cd ..

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Lambda function
        run: |
          aws lambda update-function-code \
            --function-name expense-handler \
            --zip-file fileb://lambda.zip
